### ISSUE TITLE
Another solution for URL handling 

### ISSUE THREAD

**Issue by Minishlink** [ericvicenti/universe#2]
Hello and congrats on your talk at ReactEurope!

FYI, I also played with react-navigation on the web and found another solution for handling URLs (https://github.com/Minishlink/DailyScrum/pull/29/files#diff-3c849e311ab3a495e51644824db84f77R26). Working demo [here](https://minishlink.github.io/DailyScrum/).

It comes in two parts:
- listen for browser's forward/backward and dispatch URL actions
- listen for navigation state change and update the URL accordingly

Compared to the solution you chose, it has the added benefit to keep your main Navigator stateless. (or stateful in RNav's point of view) and thus keep more universal code. It also helps detecting edge cases of RNav (I had to send [a](https://github.com/react-navigation/react-navigation/pull/4213/files) few [PR](https://github.com/react-navigation/react-navigation/pull/4219) on Rnav).

Have you any thoughts on why it'd be better or not?

Thanks!

**Comment by ericvicenti** [comment]
Thanks for your contribution on this!

A bit of feedback on this design, to help you understand why I went with the HOC approach:

- Singletons like "Navigation" and "setTopLevelNavigator" are often problematic if you do server rendering because each app should have its own navigator.
- Ideally react-native-web would not be required to use react-navigation on the web. If we continue to share "createNavigationContainer" implementation on web, it will still try to pull in react-native concepts like Linking and AsyncStorage
- Personally I'm not a big fan of refs, and would rather use controlling props where possible, preserving component encapsulation.

Those PRs to react-nav look great, will try to merge them soon!

**Comment by Minishlink** [comment]
Thanks for the explanations!

Interesting to hear about your second point, I wonder that this might be relevant in the docs/roadmap somewhere?
